apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: iam-setup
  labels:
    app.kubernetes.io/name: iam
    app.kubernetes.io/component: setup
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
      - patch

