apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "iam-migration.fullname" . }}
  labels:
    {{- include "iam-migration.labels" . | nindent 4 }}
spec:
  backoffLimit: 100
  template:
    metadata:
      labels:
        {{- include "iam-migration.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "iam-migration.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "iam-migration.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.migration.repository }}:{{ .Values.image.migration.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.migration.pullPolicy }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: iam-iam-postgres-pguser-iam
                  key: uri
            - name: DATABASE_SCHEMA
              value: {{ include "iam-postgres.username" }}
      restartPolicy: OnFailure
