apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matverseny-frontend
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://verseghy.github.io/charts/
    chart: matverseny-frontend
    targetRevision: 0.1.16
    helm:
      valuesObject:
        ingress:
          annotations:
            cert-manager.io/issuer: letsencrypt-prod
          enabled: true
          hosts:
            - host: {{ .Values.hostname }}
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - hosts:
                - {{ .Values.hostname }}
              secretName: matverseny-frontend-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace }}
  syncPolicy:
    automated: {}
