apiVersion: v1
kind: Service
metadata:
  name: {{ include "iam-mysql.fullname" . }}
  labels:
    {{- include "iam-mysql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3306
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "iam-mysql.selectorLabels" . | nindent 4 }}
