apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "matverseny-backend-setup.fullname" . }}
  labels:
    {{- include "matverseny-backend-setup.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get", "create" ]