apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: matverseny-backend-postgres
  annotations:
    postgres-operator.crunchydata.com/autoCreateUserSchema: 'true'
  labels:
    app.kubernetes.io/name: matverseny-backend
    app.kubernetes.io/component: database
spec:
  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      name: instance1
      replicas: 3
  port: 5432
  postgresVersion: 16
  users:
    - databases:
        - matverseny-backend
      name: matverseny-backend

