apiVersion: v1
kind: ServiceAccount
metadata:
  name: matverseny-backend
  labels:
    app.kubernetes.io/name: matverseny-backend
    app.kubernetes.io/component: api
automountServiceAccountToken: true

