apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matverseny-backend
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Verseghy/charts
    targetRevision: HEAD
    path: kustomize/overlays/production/matverseny-backend
  destination:
    name: verseghy-matverseny
    namespace: matverseny-backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

