apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "iam-mysql.fullname" . }}
  labels:
    {{- include "iam-mysql.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.storage }}
